# put below in your ~/.tmux.conf

# if-shell ' [ -f ~/code/configure/.tmux.conf ] ' {
#   source-file ~/code/configure/.tmux.conf
# }

# ================= settings ===================

set -g mouse on

# make vim theme works in tmux 
set -g default-terminal "xterm-256color"

set -g default-command "${SHELL}"

# The statusbar
# run-shell "~/.tmux/themes/nord-tmux/nord.tmux"
set-window-option -g window-status-current-style bg=red


set-window-option -g xterm-keys on

set -s set-clipboard on
set-option -g set-clipboard on
set-option -g history-limit 50000
